# Site settings
title: ROBOMEDON
email: marija.habijan@ferit.hr
description: >
  ROBOMEDON - Machine Learning for Precision Diagnosis and Robotic Surgery in Oncology.
  A research project funded by the Croatian Science Foundation (HRZZ).
baseurl: ""
url: "https://robomedon-ai.github.io"

github_username: robomedon-ai

# Build settings
markdown: kramdown
